In [2]:
!pip install cutensor-cu12

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 237.1/237.1 MB 5.2 MB/s eta 0:00:00


In [14]:
!pip install cupy-cuda12x

In [15]:
import cupy as cp
import cupyx as cpx

1. Scalars, Vectors, Matrices, Tensors

In [5]:
scalar = cp.array(3.0)  # scalar
vector = cp.array([1.0, 2.0, 3.0])  # vector
matrix = cp.array([[1,2,3],[4,5,6],[7,8,9]], dtype=cp.float32)  # 3x3 matrix
tensor = cp.ones((3,3,3), dtype=cp.float32)  # 3D tensor

print("Scalar:", scalar)
print("Vector:", vector)
print("Matrix:\n", matrix)
print("Tensor shape:", tensor.shape, "\n")

Scalar: 3.0
Vector: [1. 2. 3.]
Matrix:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Tensor shape: (3, 3, 3) 



2. Vector operations


In [6]:
v1 = cp.array([1,2,3], dtype=cp.float32)
v2 = cp.array([4,5,6], dtype=cp.float32)

v_add = v1 + v2
v_sub = v1 - v2
v_scalar_mul = 2 * v1
v_dot = cp.dot(v1, v2)
v_cross = cp.cross(v1, v2)

print("Vector Addition:", v_add)
print("Vector Subtraction:", v_sub)
print("Scalar Multiplication:", v_scalar_mul)
print("Dot Product:", v_dot)
print("Cross Product:", v_cross, "\n")

Vector Addition: [5. 7. 9.]
Vector Subtraction: [-3. -3. -3.]
Scalar Multiplication: [2. 4. 6.]
Dot Product: 32.0
Cross Product: [-3.  6. -3.] 



3. Matrix Operations

In [7]:
A = cp.array([[1,2],[3,4]], dtype=cp.float32)
B = cp.array([[5,6],[7,8]], dtype=cp.float32)

C_add = A + B
C_sub = A - B
C_scalar = 2 * A
C_mult = cp.matmul(A,B)
C_transpose = A.T
C_identity = cp.eye(2, dtype=cp.float32)
C_inverse = cp.linalg.inv(A)
C_det = cp.linalg.det(A)
C_normalized = A / cp.linalg.norm(A, axis=0)  # normalize columns

print("Matrix Addition:\n", C_add)
print("Matrix Subtraction:\n", C_sub)
print("Matrix Scalar Multiplication:\n", C_scalar)
print("Matrix Multiplication:\n", C_mult)
print("Matrix Transpose:\n", C_transpose)
print("Identity Matrix:\n", C_identity)
print("Inverse Matrix:\n", C_inverse)
print("Determinant:", C_det)
print("Normalized Matrix (columns):\n", C_normalized, "\n")

Matrix Addition:
 [[ 6.  8.]
 [10. 12.]]
Matrix Subtraction:
 [[-4. -4.]
 [-4. -4.]]
Matrix Scalar Multiplication:
 [[2. 4.]
 [6. 8.]]
Matrix Multiplication:
 [[19. 22.]
 [43. 50.]]
Matrix Transpose:
 [[1. 3.]
 [2. 4.]]
Identity Matrix:
 [[1. 0.]
 [0. 1.]]
Inverse Matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant: -2.0
Normalized Matrix (columns):
 [[0.31622776 0.4472136 ]
 [0.94868326 0.8944272 ]] 



4. Norms & Distance Measures


In [8]:
x = cp.array([1,2,3], dtype=cp.float32)
y = cp.array([4,5,6], dtype=cp.float32)

euclidean = cp.linalg.norm(x-y)
manhattan = cp.linalg.norm(x-y, ord=1)
cosine_sim = cp.dot(x,y) / (cp.linalg.norm(x) * cp.linalg.norm(y))

print("Euclidean Distance:", euclidean)
print("Manhattan Distance:", manhattan)
print("Cosine Similarity:", cosine_sim, "\n")

Euclidean Distance: 5.196152
Manhattan Distance: 9.0
Cosine Similarity: 0.9746318 



5. Systems of Linear Equations

In [9]:
A_sys = cp.array([[3,1],[1,2]], dtype=cp.float32)
b_sys = cp.array([9,8], dtype=cp.float32)
x_sys = cp.linalg.solve(A_sys, b_sys)

print("Solution of Ax=b:", x_sys, "\n")

Solution of Ax=b: [2. 3.] 



6. Linear Transformations

In [10]:
vec = cp.array([1,0], dtype=cp.float32)
rot_matrix = cp.array([[0, -1],[1,0]], dtype=cp.float32)  # 90 degree rotation
vec_rotated = cp.matmul(rot_matrix, vec)
print("Linear Transformation (Rotation) of vector:", vec_rotated, "\n")

Linear Transformation (Rotation) of vector: [0. 1.] 



7. Eigenvalues and Eigenvectors

In [11]:
eig_vals, eig_vecs = cp.linalg.eigh(cp.array([[2,0],[0,3]], dtype=cp.float32))
print("Eigenvalues:", eig_vals)
print("Eigenvectors:\n", eig_vecs, "\n")

Eigenvalues: [2. 3.]
Eigenvectors:
 [[1. 0.]
 [0. 1.]] 



8. Matrix Decompositions

In [16]:
# P, L, U = cpx.scipy.linalg.lu(cp.array([[4,3],[6,3]], dtype=cp.float32))
# print("LU Decomposition L:\n", L)
# print("LU Decomposition U:\n", U)

In [17]:
# QR decomposition
Q, R = cp.linalg.qr(cp.array([[1,2],[3,4]], dtype=cp.float32))
print("QR Decomposition Q:\n", Q)
print("QR Decomposition R:\n", R)

QR Decomposition Q:
 [[-0.3162278  -0.9486833 ]
 [-0.9486833   0.31622773]]
QR Decomposition R:
 [[-3.1622777 -4.4271884]
 [ 0.        -0.6324552]]


In [18]:
# SVD
U_svd, S_svd, Vh_svd = cp.linalg.svd(cp.array([[1,2],[3,4]], dtype=cp.float32))
print("SVD U:\n", U_svd)
print("SVD S:\n", S_svd)
print("SVD V^T:\n", Vh_svd, "\n")

SVD U:
 [[-0.4045536  0.9145143]
 [-0.9145143 -0.4045536]]
SVD S:
 [5.4649854 0.3659662]
SVD V^T:
 [[-0.5760484  -0.81741554]
 [-0.81741554  0.57604843]] 



9. Orthogonality & Projections

In [19]:
u = cp.array([1,0], dtype=cp.float32)
v = cp.array([0,1], dtype=cp.float32)
dot_uv = cp.dot(u,v)
proj_u_on_v = (cp.dot(u,v)/cp.dot(v,v))*v
print("Dot Product of orthogonal vectors:", dot_uv)
print("Projection of u onto v:", proj_u_on_v, "\n")

Dot Product of orthogonal vectors: 0.0
Projection of u onto v: [0. 0.] 



10. Vector Spaces & Subspaces

In [20]:
import scipy as sp

A_sub = cp.array([[1,2,3],[0,1,4],[1,3,7]], dtype=cp.float32)
rank_A = cp.linalg.matrix_rank(A_sub)
null_space = sp.linalg.null_space(A_sub.get())  # get() brings data to CPU for null space
print("Rank of A:", rank_A)
print("Null space of A:\n", null_space, "\n")

Rank of A: 2
Null space of A:
 [[ 0.7715168 ]
 [-0.6172133 ]
 [ 0.15430336]] 



11. Special Matrices

In [21]:
diag_matrix = cp.diag(cp.array([1,2,3], dtype=cp.float32))
sym_matrix = cp.array([[2,1],[1,2]], dtype=cp.float32)
orth_matrix = cp.array([[1,0],[0,-1]], dtype=cp.float32)
sparse_matrix = cp.array([[0,0,3],[0,0,0],[4,0,0]], dtype=cp.float32)

print("Diagonal Matrix:\n", diag_matrix)
print("Symmetric Matrix:\n", sym_matrix)
print("Orthogonal Matrix:\n", orth_matrix)
print("Sparse Matrix:\n", sparse_matrix)

Diagonal Matrix:
 [[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]
Symmetric Matrix:
 [[2. 1.]
 [1. 2.]]
Orthogonal Matrix:
 [[ 1.  0.]
 [ 0. -1.]]
Sparse Matrix:
 [[0. 0. 3.]
 [0. 0. 0.]
 [4. 0. 0.]]


.py

In [24]:
%%writefile gpu_linear_algebra.py

import cupy as cp
import scipy as sp

print("=== Linear Algebra Concepts on GPU using cuTENSOR/cuBLAS (via CuPy) ===\n")

# 1. Scalars, Vectors, Matrices, Tensors
scalar = cp.array(3.0)  # scalar
vector = cp.array([1.0, 2.0, 3.0])  # vector
matrix = cp.array([[1,2,3],[4,5,6],[7,8,9]], dtype=cp.float32)  # 3x3 matrix
tensor = cp.ones((3,3,3), dtype=cp.float32)  # 3D tensor

print("Scalar:", scalar)
print("Vector:", vector)
print("Matrix:\n", matrix)
print("Tensor shape:", tensor.shape, "\n")

# 2. Vector operations
v1 = cp.array([1,2,3], dtype=cp.float32)
v2 = cp.array([4,5,6], dtype=cp.float32)

v_add = v1 + v2
v_sub = v1 - v2
v_scalar_mul = 2 * v1
v_dot = cp.dot(v1, v2)
v_cross = cp.cross(v1, v2)

print("Vector Addition:", v_add)
print("Vector Subtraction:", v_sub)
print("Scalar Multiplication:", v_scalar_mul)
print("Dot Product:", v_dot)
print("Cross Product:", v_cross, "\n")

# 3. Matrix Operations
A = cp.array([[1,2],[3,4]], dtype=cp.float32)
B = cp.array([[5,6],[7,8]], dtype=cp.float32)

C_add = A + B
C_sub = A - B
C_scalar = 2 * A
C_mult = cp.matmul(A,B)
C_transpose = A.T
C_identity = cp.eye(2, dtype=cp.float32)
C_inverse = cp.linalg.inv(A)
C_det = cp.linalg.det(A)
C_normalized = A / cp.linalg.norm(A, axis=0)  # normalize columns

print("Matrix Addition:\n", C_add)
print("Matrix Subtraction:\n", C_sub)
print("Matrix Scalar Multiplication:\n", C_scalar)
print("Matrix Multiplication:\n", C_mult)
print("Matrix Transpose:\n", C_transpose)
print("Identity Matrix:\n", C_identity)
print("Inverse Matrix:\n", C_inverse)
print("Determinant:", C_det)
print("Normalized Matrix (columns):\n", C_normalized, "\n")

# 4. Norms & Distance Measures
x = cp.array([1,2,3], dtype=cp.float32)
y = cp.array([4,5,6], dtype=cp.float32)

euclidean = cp.linalg.norm(x-y)
manhattan = cp.linalg.norm(x-y, ord=1)
cosine_sim = cp.dot(x,y) / (cp.linalg.norm(x) * cp.linalg.norm(y))

print("Euclidean Distance:", euclidean)
print("Manhattan Distance:", manhattan)
print("Cosine Similarity:", cosine_sim, "\n")

# 5. Systems of Linear Equations
A_sys = cp.array([[3,1],[1,2]], dtype=cp.float32)
b_sys = cp.array([9,8], dtype=cp.float32)
x_sys = cp.linalg.solve(A_sys, b_sys)

print("Solution of Ax=b:", x_sys, "\n")

# 6. Linear Transformations
vec = cp.array([1,0], dtype=cp.float32)
rot_matrix = cp.array([[0, -1],[1,0]], dtype=cp.float32)  # 90 degree rotation
vec_rotated = cp.matmul(rot_matrix, vec)
print("Linear Transformation (Rotation) of vector:", vec_rotated, "\n")

# 7. Eigenvalues and Eigenvectors
eig_vals, eig_vecs = cp.linalg.eigh(cp.array([[2,0],[0,3]], dtype=cp.float32))
print("Eigenvalues:", eig_vals)
print("Eigenvectors:\n", eig_vecs, "\n")

# 8. Matrix Decompositions
# QR decomposition
Q, R = cp.linalg.qr(cp.array([[1,2],[3,4]], dtype=cp.float32))
print("QR Decomposition Q:\n", Q)
print("QR Decomposition R:\n", R)

# SVD
U_svd, S_svd, Vh_svd = cp.linalg.svd(cp.array([[1,2],[3,4]], dtype=cp.float32))
print("SVD U:\n", U_svd)
print("SVD S:\n", S_svd)
print("SVD V^T:\n", Vh_svd, "\n")

# 9. Orthogonality & Projections
u = cp.array([1,0], dtype=cp.float32)
v = cp.array([0,1], dtype=cp.float32)
dot_uv = cp.dot(u,v)
proj_u_on_v = (cp.dot(u,v)/cp.dot(v,v))*v
print("Dot Product of orthogonal vectors:", dot_uv)
print("Projection of u onto v:", proj_u_on_v, "\n")

# 10. Vector Spaces & Subspaces
A_sub = cp.array([[1,2,3],[0,1,4],[1,3,7]], dtype=cp.float32)
rank_A = cp.linalg.matrix_rank(A_sub)
null_space = sp.linalg.null_space(A_sub.get())  # get() brings data to CPU for null space
print("Rank of A:", rank_A)
print("Null space of A:\n", null_space, "\n")

# 11. Special Matrices
diag_matrix = cp.diag(cp.array([1,2,3], dtype=cp.float32))
sym_matrix = cp.array([[2,1],[1,2]], dtype=cp.float32)
orth_matrix = cp.array([[1,0],[0,-1]], dtype=cp.float32)
sparse_matrix = cp.array([[0,0,3],[0,0,0],[4,0,0]], dtype=cp.float32)

print("Diagonal Matrix:\n", diag_matrix)
print("Symmetric Matrix:\n", sym_matrix)
print("Orthogonal Matrix:\n", orth_matrix)
print("Sparse Matrix:\n", sparse_matrix)

Overwriting gpu_linear_algebra.py


In [25]:
!python gpu_linear_algebra.py

=== Linear Algebra Concepts on GPU using cuTENSOR/cuBLAS (via CuPy) ===

Scalar: 3.0
Vector: [1. 2. 3.]
Matrix:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Tensor shape: (3, 3, 3) 

Vector Addition: [5. 7. 9.]
Vector Subtraction: [-3. -3. -3.]
Scalar Multiplication: [2. 4. 6.]
Dot Product: 32.0
Cross Product: [-3.  6. -3.] 

Matrix Addition:
 [[ 6.  8.]
 [10. 12.]]
Matrix Subtraction:
 [[-4. -4.]
 [-4. -4.]]
Matrix Scalar Multiplication:
 [[2. 4.]
 [6. 8.]]
Matrix Multiplication:
 [[19. 22.]
 [43. 50.]]
Matrix Transpose:
 [[1. 3.]
 [2. 4.]]
Identity Matrix:
 [[1. 0.]
 [0. 1.]]
Inverse Matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant: -2.0
Normalized Matrix (columns):
 [[0.31622776 0.4472136 ]
 [0.94868326 0.8944272 ]] 

Euclidean Distance: 5.196152
Manhattan Distance: 9.0
Cosine Similarity: 0.9746318 

Solution of Ax=b: [2. 3.] 

Linear Transformation (Rotation) of vector: [0. 1.] 

Eigenvalues: [2. 3.]
Eigenvectors:
 [[1. 0.]
 [0. 1.]] 

QR Decomposition Q:
 [[-0.3162278  -0.9486833 ]
 [-0.9